version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/powerBackEnd"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/powerReactApp"
    schedule:
      interval: "weekly"
